apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-feed
  labels:
    app: udagram-api-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-api-feed
  template:
    metadata:
      labels:
        app: udagram-api-feed
    spec:
      containers:
        - name: udagram-api-feed
          image: filipjnc/udagram-api-feed:v1
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 8080
