apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-reverseproxy
  labels:
    service: udagram-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-reverseproxy
  template:
    metadata:
      labels:
        service: udagram-reverseproxy
    spec:
      containers:
        - name: udagram-reverseproxy
          image: filipjnc/udagram-reverseproxy:v2
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
