apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-api-user
  labels:
    service: udagram-api-user
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-api-user
  template:
    metadata:
      labels:
        service: udagram-api-user
    spec:
      containers:
        - name: udagram-api-user
          image: filipjnc/udagram-api-user:v2
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
