apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-frontend
  labels:
    service: udagram-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      service: udagram-frontend
  template:
    metadata:
      labels:
        service: udagram-frontend
    spec:
      containers:
        - name: udagram-frontend
          image: filipjnc/udagram-frontend:v5
          envFrom:
            - secretRef:
                name: env-secret
            - configMapRef:
                name: env-config
          ports:
            - containerPort: 80
          imagePullPolicy: Always
